---
# tasks file for ansible_deployer
- name: Removing "{{ production_server }}" from LoadBalancer Pools
  command: sed -i.bak 's/server prod-server-1 10.1.1.31:80/#server prod-server-1 10.1.1.31:80/g' /etc/haproxy/haproxy.cfg
  become: true
  when: inventory_hostname == 'lb-server'

- name: Restart haproxy service
  service:
    name: haproxy
    state: restarted
  become: true
  register: disable_prod
  when: inventory_hostname == 'lb-server'

- name: Deploy backend app on "{{ production_server }}"
  docker_container:
    name: go-sample-be-app
    image: "khhini/go-sample-app:{{IMAGE_TAG}}"
    state: started
    recreate: yes
    restart_policy: always
    command: ["sh", "-c", "app -port=8080"]
    published_ports:
      - 8081:8080
  register: prod_deployment
  when: inventory_hostname == production_server and disable_prod is succeeded

- name: Checking backend "{{production_server}}" ready to handle request
  uri:
    url: http://{{production_server}}:8081/healthz
  register: prod_hc
  when: inventory_hostname == 'lb-server' and prod_deployment is succeeded

- name: Deploy frontend app on "{{ production_server }}"
  docker_container:
    name: go-sample-fe-app
    image: "khhini/go-sample-app:{{IMAGE_TAG}}"
    state: started
    recreate: yes
    restart_policy: always
    command: ["sh", "-c", "app -frontend=true -backend-service=http://10.1.1.10:8081 -port=80"]
    published_ports:
      - 80:80
  register: prod_deployment
  when: inventory_hostname == production_server and disable_prod is succeeded

- name: Checking frontend "{{production_server}}" ready to handle request
  uri:
    url: http://{{production_server}}/healthz
  register: prod_hc
  when: inventory_hostname == 'lb-server' and prod_deployment is succeeded

- name: Register "{{ production_server }}" to LoadBalancer Pools
  command: sed -i.bak 's/#server {{ production_server }}/server {{ production_server }}/g' /etc/haproxy/haproxy.cfg
  become: true
  when: inventory_hostname == 'lb-server' and prod_hc is succeeded

- name: Restart haproxy service
  service:
    name: haproxy
    state: restarted
  become: true
  when: inventory_hostname == 'lb-server'
